[project]
name = "embedder"
version = "0.1.0"
description = "app for answering user questions about existing data"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "openai>=3.14.0",
    "python-dotenv>=1.2.3",
    "uvicorn>=0.53.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
